services:
  backend:
    build:
      context: ./backend
    # PRODUCTION COMMAND: Không dùng --reload, tăng workers nếu cần
    # Ở đây em dùng 1 worker mặc định, nếu máy mạnh có thể tăng lên (vd: --workers 4)
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    # Trong Prod, thường ta không mount volume code (/app) để đảm bảo code trong container là cố định
    # Tuy nhiên, nếu anh muốn sửa file .env dễ dàng thì vẫn giữ env_file
    ports:
      - "8000:8000" # Có thể đóng port này lại nếu chỉ muốn truy cập qua Nginx (Frontend)
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ENVIRONMENT=production
    restart: always

  worker:
    build: { context: ./backend }
    command: celery -A celery_worker.celery_app worker --loglevel=info -P gevent --concurrency=100
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on: [ db, cache, backend ]
    restart: always

  beat:
    build: { context: ./backend }
    command: celery -A celery_worker.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on: [ db, cache, backend ]
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Sử dụng Dockerfile production vừa tạo
    ports:
      - "80:80" # Chạy trên cổng 80 chuẩn (http://localhost)
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

volumes:
  postgres_data: